import { writeFileSync } from "fs";
import { join } from "path";

export function generateReport(results) {
  const date = new Date().toLocaleString();
  const totalFiles = results.length;
  const totalFunctions = results.reduce((sum, r) => sum + r.functions.length, 0);
  const totalTests = results.reduce((sum, r) => sum + r.functions.length, 0);

  let md = `# 🧪 Test Generation Report
Generated on: ${date}

---

## 📊 Summary

| Item | Count |
|------|-------|
| Files Processed | ${totalFiles} |
| Functions Found | ${totalFunctions} |
| Test Files Generated | ${totalTests} |

---

## 📄 File Breakdown

`;

  for (const result of results) {
    md += `### 📁 ${result.filename} (${result.language})\n\n`;

    if (result.error) {
      md += `> ❌ Error: ${result.error}\n\n`;
      continue;
    }

    if (result.functions.length === 0) {
      md += `> ⚠️ No functions found\n\n`;
      continue;
    }

    md += `| Function | Params | Test File |\n`;
    md += `|----------|--------|-----------|\n`;

    for (const fn of result.functions) {
      const params = fn.params.length ? fn.params.join(", ") : "none";
      md += `| \`${fn.name}\` | \`${params}\` | \`${fn.name}.test.js\` |\n`;
    }

    md += `\n`;
  }

  md += `---

## ✅ What Was Covered

- Happy path (normal inputs)
- Edge cases (empty, zero, large values)
- Error cases (invalid inputs, throws)
- Boundary values

---

## ⚠️ What To Do Next

- Run the generated tests using Jest or your test runner
- Review edge cases manually for business logic
- Add integration tests for functions that call each other

---

*Generated by AI Test Case Generator*
`;

  return md;
}